galaxyproject/bioblend

- bioblend/galaxy/objects/wrappers.py
- tests/TestGalaxyObjects.py
As explained in issue #108 , ```input_ids``` Workflow attribute is not properly defined: it seems to be the same of ```data_input_ids``` attribute (i.e. ids of the workflow data inputs), while it is the set of ids of the source vertices of the workflow DAG, which can be either tools or data_inputs. Similarly for ```output_ids```.
I propose to rename both ```input_ids``` and ```output_ids``` to ```source_ids``` and ```sink_ids``` respectively to avoid confusion, even if this will remove these attributes from the Workflow objects.
> Rename input_ids and output_ids Workflow attributes to source_ids and sink_ids respectively

- bioblend/galaxy/objects/wrappers.py
- tests/TestGalaxyObjects.py
I don't know exactly why the removing of the initial 'F' was done in the first place, so opening a PR.
> Restore initial 'F' in library folder IDs. Fix #111.

- bioblend/galaxy/objects/wrappers.py
As per discussion in #114, simply uses the 'parent_id' value in the wrapped Folder data to fetch the indicated parent Folder and set as the current Folder's 'parent' attribute.
> non-root Folder automatically gets parent attribute

- bioblend/galaxy/datasets/__init__.py
- bioblend/galaxy/folders/__init__.py
- bioblend/galaxy/forms/__init__.py
- bioblend/galaxy/genomes/__init__.py
- bioblend/galaxy/groups/__init__.py
- bioblend/galaxy/histories/__init__.py
- bioblend/galaxy/jobs/__init__.py
- bioblend/galaxy/libraries/__init__.py
- bioblend/galaxy/quotas/__init__.py
- bioblend/galaxy/roles/__init__.py
- bioblend/galaxy/tool_data/__init__.py
- bioblend/galaxy/tools/__init__.py
- bioblend/galaxy/toolshed/__init__.py
- bioblend/galaxy/users/__init__.py
- bioblend/galaxy/visual/__init__.py
- bioblend/galaxy/workflows/__init__.py
Modify bioblend.galaxy.histories to implement TODOs, fix dataset URL by downloading from url provided by show_datasets() call.
This doesn't pass test cases on my desktop (but then again, reverting to the parent commit also didn't let it pass tests), so I'm going to let Travis test it and rely on those test results.
There is a small behaviour change here:
| file_path | use_default_filename | original output | new output
--- | --- | --- | ----
`str` (folder) | True | None | return path the file was saved to, rather than leaving the user guessing/calculating
`str` (file) | False| None | return the user requested path that the file was saved to
None | True or False | file contents | file contents
The other small behaviour change being that `download_dataset` in `bioblend.galaxy.histories` now …
> Fix for #84 and documentation improvements

- .travis.yml
Easier than setting up jenkins jobs for ALL the things.
-  Adds an [environment variable](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix) for galaxy version, in response to discussion https://github.com/erasche/bioblend/commit/dd89790104f00a358f8ae16905364e558ffae8c9#commitcomment-10027726
- Only support relatively recent builds in order to avoid messiness with lack of user-add API route (according to @nsoranzo), and the switch from `universe_wsgi.ini` to `galaxy.ini`
> matrix builds for recent galaxy releases

- bioblend/toolshed/repositories/__init__.py
I misread https://github.com/galaxyproject/galaxy/pull/2 and failed to notice the `[]` at the end of `category_ids`.
> Missing brackets in API url parameter

- bioblend/galaxy/__init__.py
- bioblend/galaxy/datasets/__init__.py
- bioblend/galaxyclient.py
- bioblend/toolshed/__init__.py
I think we should stay on the safe side, also [requests](http://python-requests.org/) has [SSL cert verification](http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification) set to True by default.
> Verify SSL certificates by default.

- bioblend/galaxy/objects/wrappers.py
I have added a check to verify that every tool in the workflow exists in the Galaxy instance
without this check,  workflow.is_runnable return True
> add check to verify existence of the tools of the workflow

- bioblend/cloudman/launch.py
This pull request fixes two issues with boto.
* Fixes an [issue](https://github.com/galaxyproject/cloudlaunch/issues/47) with inter-node communication permissions. It seems that boto's authorize method still requires the ip_protocol, source port (0) and destination port (65535) along with the src_group parameter.
* Boto has an [issue](https://github.com/boto/boto/issues/350) with specifying a subnet and a groupName simultaneously. The solution described by this thread seems to be specifying the subnet_id's instead of the subnet name.
Let me know what you want to see here.
2. When I pass a subnet_id to boto's ```run_instances``` method, I get the following error. This seems to be a incompletely addressed idiosyncracy of the boto library and how it prefers for subnets to be specified. See …
> Adds subnet_id to launch method.

- .travis.yml
- bioblend/galaxy/client.py
- bioblend/galaxy/workflows/__init__.py
- tests/TestGalaxyWorkflows.py
- tests/data/test_workflow_pause.ga
- Deprecate ``run_workflow`` in favor in ``invoke_workflow`` which runs workflows in the background and has superior input handling.
- Add set of methods for interfacing with invocations via the API (get, show, cancel).
- Add methods for interfacing with workflow invocation steps (show, run action).
- Add tests that exercises all of this with a workflow that contains a pause step.
Closes #153.
Meta Commentary: Giving an API tutorial at a workshop at the festival of genomics Tuesday so if this can be reviewed, merged, and in a released bioblend by midday Monday I'd totally buy people involved a beer or three :cold_sweat:.
> Implement client for a modern workflow API.

- CHANGELOG.md
- bioblend/toolshed/__init__.py
- bioblend/toolshed/categories/__init__.py
- bioblend/toolshed/repositories/__init__.py
- bioblend/toolshed/tools/__init__.py
- docs/api_docs/toolshed/all.rst
Rename `bioblend.toolshed.repositories.ToolShedClient` class to
`bioblend.toolshed.repositories.ToolShedRepositoryClient` .
Rename `bioblend.toolshed.tools.ToolShedClient` class to
`bioblend.toolshed.tools.ToolShedToolClient` .
Ping @afgane: you added the `bioblend.toolshed.repositories.get_categories()` method in de600e1635ac70252d2b921ee6c24f27760ae0cb, but I think it never worked.
> Add bioblend.toolshed.categories.ToolShedCategoryClient .

- CHANGELOG.md
- bioblend/__init__.py
- bioblend/galaxy/client.py
- bioblend/galaxy/groups/__init__.py
- bioblend/galaxy/histories/__init__.py
- bioblend/galaxy/objects/wrappers.py
- bioblend/galaxyclient.py
- tests/TestGalaxyHistories.py
- tests/TestGalaxyObjects.py
Also:
- modify `GalaxyClient.make_put_request()` to return the decoded response content
- added `update()` method to `HistoryDatasetAssociation`.
Asking for a review since this slightly modifies our API.
> Modify update methods of HistoryClient to return the details instead of the status code.

- bioblend/galaxy/toolshed/__init__.py
This goes together with https://github.com/galaxyproject/galaxy/pull/2554.
On older galaxy instances install_resolver_dependencies will be silently ignored.
Is that okay or should we explicitly check the galaxy version?
ping @nsoranzo
> Add install_resolver_dependencies keyword to install_repository_revision

- ABOUT.rst
- README.rst
This is not cloudman: http://usecloudman.org :)
Thanks for reporting @blankclemens
> Fix link to cloudman

- CHANGELOG.md
- bioblend/galaxy/config/__init__.py
- bioblend/galaxy/toolshed/__init__.py
- bioblend/galaxy/users/__init__.py
As I'm playing more with parsec, I'm finding some other features not well covered so here's a PR with them. It is not a coherent collection of stuff, my apologies.
- get_users now supports server side filtering that's available
- there's a function to get a user's API key without resetting it.
- /api/version
> More API Coverage

- bioblend/galaxy/datasets/__init__.py
Otherwise the file is downloaded in memory for the check.
Reported by @glormph.
> Check for mismatching content size only when not streaming to file

- bioblend/_tests/TestGalaxyRoles.py
- bioblend/galaxy/roles/__init__.py
This PR will enable the admin users to create a new role using Bioblend.
> 'create_role' method for BioBlend

- bioblend/galaxy/objects/galaxy_instance.py
to match what's available in the regular API. For example, the following works:
from bioblend.galaxy import GalaxyInstance
gi = GalaxyInstance(url=..., key=..., verify=False)
but this isn't possible without this PR:
from bioblend.galaxy.objects import GalaxyInstance
gi = GalaxyInstance(url=..., api_key=..., verify=False)
> Add a verify option when using the object-oriented API

- bioblend/_tests/TestGalaxyLibraries.py
- bioblend/_tests/TestGalaxyObjects.py
- bioblend/galaxy/client.py
- bioblend/galaxy/libraries/__init__.py
- bioblend/galaxy/objects/wrappers.py
- bioblend/galaxyclient.py
Hi,
Here's a little update to the data library api:
- add library dataset update method
- add `preserve_dirs` and `tag_using_filenames` arguments when loading data into a data library
> Add missing api method/arg for data libraries

- bioblend/galaxy/workflows/__init__.py
Using repeat parameters is quite tricky, and is not made explicit anywhere but in Galaxy API tests.
> Explains how to work with <repeat /> parameters

- docs/api_docs/galaxy/docs.rst
Add documentation on how to use bioblend to ship the request to the Galaxy API. This could be used to avoid having both requests and bioblend used in a single script that needs administrative privileges to access Galaxy or does API transactions that bioblend does not yet support.
> Documentation on 'raw' API usage through bioblend

- bioblend/galaxy/jobs/__init__.py
Added function to get the job metrics for a specified job. `show_job` offers this functionality in part, however the Galaxy API in that case only returns metrics if the user is an admin. This call allows to fetch metrics even as a normal user as long as the Galaxy instance has `expose_potentially_sensitive_job_metrics` set to true.
> Get job metrics

- bioblend/toolshed/repositories/__init__.py
This fixes the following error I get when trying to get the list of revisions for a tool from the toolshed:
```
File "/home/abretaud/miniconda3/lib/python3.7/site-packages/bioblend/toolshed/repositories/__init__.py", line 144, in get_ordered_installable_revisions
url = self.url + '/get_ordered_installable_revisions'
AttributeError: 'ToolShedRepositoryClient' object has no attribute 'url'
```
What surprises me is that this usegalaxy.eu script should be failing without this patch, but somehow tools get updated: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/scripts/update-tool.py#L35
> Fix error with toolshed get_ordered_installable_revisions and get_repository_revision_install_info

- .travis.yml
- ABOUT.rst
- CHANGELOG.md
- README.rst
- bioblend/_tests/TestGalaxyFolders.py
- bioblend/_tests/TestGalaxyHistories.py
- bioblend/_tests/TestGalaxyLibraries.py
- bioblend/_tests/TestGalaxyObjects.py
- bioblend/_tests/TestGalaxyTools.py
- bioblend/_tests/TestGalaxyUsers.py
- bioblend/_tests/TestGalaxyWorkflows.py
- bioblend/galaxy/config/__init__.py
- bioblend/galaxy/histories/__init__.py
- bioblend/galaxy/libraries/__init__.py
- bioblend/galaxy/objects/wrappers.py
- bioblend/galaxy/tools/__init__.py
- bioblend/galaxy/toolshed/__init__.py
- bioblend/galaxy/users/__init__.py
- run_galaxy.sh
- Install virtualenv >=20.0.14 to fix conda commands on macOS
- Use Ubuntu bionic for TravisCI
- Deploy under Python 3.7
- Update psycopg2 requirement to a version compatible with glibc 2.26 for Galaxy releases 16.01-18.01
- Drop support for old Galaxy releases 15.03 - 17.05 which don't start without multiple patches due to broken Python eggs/wheels download: see e.g. https://travis-ci.org/github/galaxyproject/bioblend/builds/665803989 for eggs, while for wheels the psycopg2 fix above doesn't work without passing the `--extra-index-url` option to `pip`
> Fix TravisCI. Drop support for Galaxy <=17.05

- bioblend/_tests/TestGalaxyDatasets.py
- bioblend/galaxy/datasets/__init__.py
Add function to access `/api/datasets` to get a list of all datasets, with `limit` and `offset` parameters.
> Add get_datasets() function

- bioblend/galaxyclient.py
I accidentally came across this bug while doing some work with `planemo run`.
If the URL is accidentally specified with `http://` rather than `https://`, POST requests seem not to work properly; instead, they get redirected to a GET request with the same URL. So the POST request fails, but the user is not informed, because they receive the result of a different (unintended) API call, and a status code of 200.
For example, the following:
```
http_gi = galaxy.GalaxyInstance(key='APIKEY', url='http://usegalaxy.eu/')
http_gi.histories.create_history('test')
```
will not create a history. Instead, the POST request to http://usegalaxy.eu/api/histories is redirected as a GET request, so the user just gets a list of all their histories, without any error raised.
This PR simply adds a check that …
> Do not redirect non-GET requests

- bioblend/_tests/TestGalaxyHistories.py
- bioblend/galaxy/histories/__init__.py
To make it clear in the documentation that datatypes can be modified through bioblend.
Fixes #243.
> Add documentation for datatype updates

- bioblend/galaxyclient.py
in GalaxyClient.make_get_request()
As mentioned by @nsoranzo in galaxyproject/galaxy#11375. This also fixes the 'key' error when making an API request.
Not sure if I did it right, but it's a starting point.
> replace param 'key' with header 'x-api-key'

- bioblend/_tests/TestGalaxyJobs.py
- bioblend/galaxy/jobs/__init__.py
The parameters `workflow_id`, `invocation_id`, `limit`, `offset` are not yet implemented in Galaxy, Maybe `user_id` filtering for admins would be nice as well, just like in get_invocations.
Related issue: #373
> JobsClient.get_jobs method filtering

- bioblend/_tests/TestGalaxyToolDependencies.py
- bioblend/galaxy/__init__.py
- bioblend/galaxy/tool_dependencies/__init__.py
Add file for ToolDependencies API with a function `summarize_toolbox` plus a test file.
https://docs.galaxyproject.org/en/master/api/api.html#module-galaxy.webapps.galaxy.api.tool_dependencies
> Add function to get /dependency_resolvers/toolbox

- bioblend/_tests/TestGalaxyJobs.py
- bioblend/galaxy/jobs/__init__.py
Adds the following new parameters to `get_jobs()`:
- `user_id`
- `limit`
- `offset`
- `workflow_id`
- `invocation_id`
This requires changes to the Galaxy `api/jobs` endpoint.
See: galaxyproject/galaxy#11560
> Add more filtering parameters to JobsClient.get_jobs()

- bioblend/_tests/TestGalaxyJobs.py
- bioblend/galaxy/jobs/__init__.py
Add the following methods to JobsClient:
- `get_common_problems()`
- `get_inputs()`
- `get_outputs()`
- `resume_job()`
- `get_destination_params()`
- `show_job_lock()`
- `update_job_lock()`
As well as corresponding tests and a helper function `_run_tool()`.
> Improve coverage of the jobs API

- bioblend/_tests/TestGalaxyDatasets.py
- bioblend/galaxy/datasets/__init__.py
The API endpoint is quite complex so I split it into two methods: a simple publish/unpublish and a more complex one in which role IDs can be assigned to different permissions.
> Add methods to DatasetClient for modifying permissions

- bioblend/cloudman/__init__.py
- bioblend/cloudman/launch.py
When starting with configuration option use_ssl True, cloudman must use https to communicate with the instance throughout. Some of the initial setup steps assume only http is needed.
> Handle HTTPS Cloudman instances better

- bioblend/_tests/TestGalaxyUsers.py
It occurred to me it would be useful to have a test for email/password authentication (see https://github.com/galaxyproject/bioblend/issues/398). This seemed like the most logical place to add it.
> Add test for authentication with email and password

- bioblend/galaxy/jobs/__init__.py
The `tool_inputs` dictionary which is submitted to run a tool can be quite complicated. Here's an example from the `gmx_sim` tool:
```
{'gro_input': {'values': [{'id': '5c2304bef5249942',
'src': 'hda'}]},
'top_input': {'values': [{'id': 'a624b4df4f58d2a8',
'src': 'hda'}]},
'inps': {'cpt_in': {'values': [{'id': 'e582474250398d8f',
'src': 'hda'}]},
'itp_in': None,
'ndx_in': {'values': [{'id': '3b4c7a3e3f7b8f6a',
'src': 'hda'}]}},
'outps': {'traj': 'xtc',
'str': 'gro',
'cpt_out': 'false',
'edr_out': 'false',
'xvg_out': 'true',
'tpr_out': 'true'},
'sets': {'ensemble': 'nvt',
'mdp': {'mdpfile': 'custom',
'mdp_input': {'values': [{'id': 'ac6eff99a4eb515d',
'src': 'hda'}]}}},
'capture_log': 'true'}
```
With the current implementation, if a user wants to rerun a job run with the set of parameters …
> Make `tool_inputs_update` argument of `gi.jobs.rerun_job()` more flexible

- bioblend/galaxy/client.py
- bioblend/galaxy/groups/__init__.py
- bioblend/galaxy/histories/__init__.py
- bioblend/galaxy/jobs/__init__.py
- bioblend/galaxy/tools/__init__.py
- bioblend/galaxyclient.py
Otherwise we send a request body that is `b"null"` (instead of `b""`), which is a problem for the Galaxy API. This means we could drop the `payload={}` we have in many places of the code.
> Only use json.dump if payload is not None

- bioblend/_tests/TestGalaxyTools.py
- bioblend/galaxy/tools/__init__.py
Add `reload` function to bioblend.galaxy.tools.
This reloads a single tool and can be useful if a wrapper has been altered.  I can't think of a way to test this.
> Add GET /api/tools/{tool_id}/reload

- bioblend/_tests/TestGalaxyTools.py
- bioblend/galaxy/tools/__init__.py
I added the `build` method, which is equivalent to the internal galaxy API functionality `build`. It's useful to get a tool model including dynamic parameters and updated values, repeats block, etc. based on a bioblend API call. A use case can be found in my current project (https://github.com/jaidevjoshi83/galaxylab.git) where bioblend API is being used to create galaxy Tool GUI within Jupyterlab Notebooks.  Since tool forms need to be updated based on selected dynamic parameters therefor this functionality is very useful. 
Thanks
> Class method 'build' added to get a tool model including dynamic parameters. 

- bioblend/galaxy/invocations/__init__.py
Type annotating `invocations`.
Validating with: `tox -e lint`
Still working on this. Here is the result of the linting:
```bash
lint run-test: commands[0] | flake8 .
lint run-test: commands[1] | black --check --diff .
All done! ✨ 🍰 ✨
114 files would be left unchanged.
lint run-test: commands[2] | isort --check --diff .
Skipped 3 files
lint run-test: commands[3] | mypy bioblend/
bioblend/galaxy/invocations/__init__.py:442: error: "GalaxyClient" has no attribute "invocations"  [attr-defined]
invocation = self.gi.invocations.show_invocation(invocation_id)
^
Found 1 error in 1 file (checked 67 source files)
ERROR: InvocationError for command /Users/fabio/GitHub/bioblend/.tox/lint/bin/mypy bioblend/ (exited with code 1)
__________________________________________________________________ summary …
```
> `invocations`: Type Annotations

- bioblend/galaxy/forms/__init__.py
> `forms`: Type Annotations

- bioblend/galaxy/jobs/__init__.py
> `jobs`: Type Annotations

- bioblend/__init__.py
Type annotating `bioblend.__init__.py`.
It also involved `_tests/GalaxyTestBase.py` and `_tests/TestGalaxyObjects.py`.
> `bioblend.__init__.py`: Type Annotations

- bioblend/toolshed/tools/__init__.py
Type annotating `toolshed.tools`.
> `toolshed.tools`: Type Annotations

- bioblend/toolshed/categories/__init__.py
Type annotating `toolshed.categories`.
> `toolshed.categories`: Type Annotations

- bioblend/toolshed/__init__.py
> `toolshed`: Type Annotations

- CHANGELOG.md
- bioblend/config.py
If needed, use the methods inherited from `configparser.ConfigParser` instead.
Also:
- Type annotations.
> Remove unused methods from ``bioblend.config.Config``

- bioblend/galaxy/client.py
deleting a history returns code 202 in Galaxy 22.05
> Handle delete returning code 202

- bioblend/galaxy/workflows/__init__.py
Add argument `require_exact_tool_versions` (new in 22.05) to invoke_workflow.  This is true by default but can be set to False in the params.
> Add argument `require_exact_tool_versions` to `invoke_workflow`

- bioblend/galaxy/users/__init__.py
I have an extra_user_preference configured, relevant section of user_preferences_extra_conf.yml of my galaxy config:
```yaml
preferences:
bpadp:
description: Bpa Data Portal API token
inputs:
- name: api_token
label: Api Token
type: text
required: False
```
This translates into a preference key called "bpadp|api_token" which cannot be passed into UserClient.update_user as a kwarg ("|" is a forbidden character in python variables). I updated update_user to accept a dict as second positional parameter, allowing updating such preferences Ala:
`update_user("someID",{"bpadp|api_token":"value"})`
The change is backwards compatible and still supports kwargs passing.
> allow changing extra_user_preferences via update_user call.

- bioblend/_tests/TestGalaxyHistories.py
- bioblend/galaxy/histories/__init__.py
Add filtering for `create_time-ge`, `create_time-le`,  `update_time-ge`, `update_time-le` for histories using the same keywords as used in `get_datasets` filtering. A lot of this is reused from `datasets/__init__.py` .
> Time filters for histories.get_histories

- bioblend/_tests/TestGalaxyHistories.py
- bioblend/galaxy/histories/__init__.py
Adding `keys`, `limit` and `offset` are necessary for updating Galaxy Australia's history management script to use bioblend.
> Add view, keys, limit and offset to get_histories

- bioblend/_tests/TestGalaxyHistories.py
- bioblend/galaxy/dataset_collections/__init__.py
- bioblend/galaxy/histories/__init__.py
Followup on https://github.com/galaxyproject/bioblend/pull/484/ ping @cat-bro
> Fix docs for `offset` in `get_histories` and add test

- CHANGELOG.md
- bioblend/galaxy/quotas/__init__.py
Currently untested, since the test instance would need an object store setup. If easy to setup I could do it (usually testing is a good idea :) )
> Add ``quota_source_label`` parameter to ``QuotaClient.create_quota()``
