galaxyproject/bioblend

README.rst

Landscape is becoming quite popular and a number of other galaxy projects use it for monitoring code smell/issues.

Add landscape.io badge

---

bioblend/toolshed/repositories/__init__.py

Defaulted to "unrestricted" rather than None as that seemed to make more sense.

Fixes #116

---

CHANGELOG.md

@afgane I wanted to request a release so I can close galaxyproject/planemo#88 but I didn't want to make you do a bunch of extra work. Feel free to ignore, modify, request changes, etc...

Outline possible entries for 0.5.3 in CHANGELOG.md.

---

bioblend/__init__.py
bioblend/cloudman/__init__.py
bioblend/cloudman/launch.py
bioblend/config.py
bioblend/galaxy/__init__.py
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/objects/client.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxyclient.py
bioblend/toolshed/__init__.py
bioblend/toolshed/repositories/__init__.py
docs/examples/objects/w5_galaxy_api.py
setup.py
tests/GalaxyTestBase.py
tests/TestGalaxyObjects.py

TODO: dictionary iterator methods.
Also, still not possible to test on Python3 because of poster and boto packages.

WIP: Add support for Python >= 3.3 using six package.

---

bioblend/galaxy/histories/__init__.py
bioblend/galaxy/objects/client.py
bioblend/galaxy/workflows/__init__.py

Remove parameters deprecated in v0.5.3 .

---

bioblend/galaxy/tools/__init__.py
docs/api_docs/galaxy/docs.rst

Covers uploading via HTTP and FTP

Add support for uploading (importing) from FTP, and associated examples

---

bioblend/cloudman/__init__.py

@afgane Oops, not sure how we missed this - but none of the flavour data was getting passed across.

Fixed to bug where extra parameters were not being passed as userdata.

---

bioblend/galaxy/histories/__init__.py

The collection_description parameter should expect a collections.CollectionDescription instead of a str.

Update param type for create_dataset_collection()

---

bioblend/cloudman/launch.py

dadf70908722cb2c2323d07d01525b7af42739e3
@afgane This fixes the problem I mentioned the other day of security groups not being applied. Turned out that this occurred during the VPC enhancement: https://github.com/galaxyproject/bioblend/commit/dadf70908722cb2c2323d07d01525b7af42739e3#diff-7e70471be8164da6274e355439a49a22R176
The classic security groups were replaced with security_group_ids - however, the create_security_groups method does not return ids for classic groups.

Add back ec2 classic security groups removed in commit:

---

bioblend/cloudman/launch.py

This is not a particularly good place for this fix - but in the current code,
there aren't many options. We can't do this on the cloudlaunch side
since cloudlaunch doesn't have an ec2 connection. We can't do this
properly on the bioblend side because the public IP is assigned after an
indeterminate waiting period, and there's no monitoring thread in which to do this. Hopefully, the pending rewrite will fix this properly.

Temporary fix for lack of floating ips

---

bioblend/galaxy/datasets/__init__.py

I had to download datasets >20GB today and my processes got killed :(. So I changed the requests.get code in bioblend to accept streams and download in chunks to a file. Not much work and solved my problems. Hope it fits the project. :)

Stream downloaded datasets to file

---

bioblend/galaxy/histories/__init__.py

Ok so I just had to figure out how to pass the CollectionDescription parameter. Pretty easy but I still thought I might as well write an example for the docs.

Wrote a small example parameter for create_dataset_collection

---

CHANGELOG.md
bioblend/galaxy/objects/client.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxy/workflows/__init__.py
docs/api_docs/galaxy/docs.rst
tests/TestGalaxyHistories.py
tests/TestGalaxyObjects.py
tests/TestGalaxyTools.py
tests/TestGalaxyWorkflows.py
tests/test_util.py

Inspired by #200, thanks @manabuishii.

Deprecate import_workflow_json and export_workflow_json in favor of import_workflow_dict and export_workflow_dict

---

.travis.yml
bioblend/galaxy/tools/__init__.py
run_bioblend_tests.sh
tests/TestGalaxyTools.py

Add tool-centric API endpoint to install dependencies

---

bioblend/_tests/GalaxyTestBase.py
bioblend/_tests/TestGalaxyTools.py
bioblend/_tests/test_util.py

First round of fixes for running ``bioblend-galaxy-tests`` against planemo-machine. See individual commits for individual descriptions.

Test fixes for planemo machine

---

bioblend/_tests/TestGalaxyFolders.py
bioblend/_tests/TestGalaxyLibraries.py
bioblend/galaxy/folders/__init__.py

Implements support for:
- creating folder
- updating folder
- getting folder permissions
- setting folder permissions

Fixes #166

---

CHANGELOG.md
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/workflows/__init__.py

xref. https://github.com/galaxyproject/bioblend/issues/221 and https://github.com/galaxyproject/galaxy/issues/4014

Deprecate show_stderr() and show_stdout() methods of DatasetClient

---

bioblend/galaxyclient.py

Tried to delete a history with parsec, my server threw an error.

JSON header needed for delete too

---

setup.py

See https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
Also revise indentation and update homepage URL.

Add 'testing' extra as dynamic dependency of 'bioblend-galaxy-tests' entry point

---

bioblend/galaxy/toolshed/__init__.py

Fixes #260 ping @mvdbeek wanna add the ephemeris equivalent?

Add uninstall function

---

bioblend/_tests/TestGalaxyLibraries.py
bioblend/galaxy/libraries/__init__.py

let the user get and set permissions at the dataset level

add get_dataset_permissions and set_dataset_permissions functions

---

bioblend/_tests/TestGalaxyLibraries.py
bioblend/galaxy/libraries/__init__.py

This is the corresponding changes to the API change in https://github.com/galaxyproject/galaxy/pull/8530

Add support for tagging library datasets

---

bioblend/_tests/TestGalaxyLibraries.py

xref. https://github.com/galaxyproject/galaxy/pull/8976

Update library tag tests for Galaxy 19.09 fixes

---

bioblend/_tests/TestGalaxyWorkflows.py
bioblend/galaxy/workflows/__init__.py

Also add ``version`` parameter to ``show_workflow()`` and ``export_workflow_dict()`` methods of ``WorkflowClient``

Add ``update_workflow()`` method to ``WorkflowClient``

---

.travis.yml
ABOUT.rst
CHANGELOG.md
README.rst
bioblend/_tests/TestGalaxyFolders.py
bioblend/_tests/TestGalaxyLibraries.py
bioblend/_tests/TestGalaxyObjects.py
bioblend/_tests/TestGalaxyToolData.py
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/libraries/__init__.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxy/users/__init__.py

Fix https://github.com/galaxyproject/bioblend/issues/304 .

Drop support for Galaxy releases 14.10 and 15.01

---

.travis.yml
Makefile
docs/index.rst
run_bioblend_tests.sh
tox.ini

Also use ``python -m pip install`` syntax as recommended in: https://docs.python.org/3/installing/index.html#basic-usage

Add lint and deploy stages to TravisCI configuration

---

bioblend/_tests/TestGalaxyDatasets.py
bioblend/_tests/TestGalaxyHistories.py
bioblend/_tests/TestGalaxyObjects.py
bioblend/_tests/TestGalaxyTools.py
bioblend/galaxy/histories/__init__.py

@mtekman, think this is PR-ready.
Fixes https://github.com/galaxyproject/bioblend/issues/280.

Function to copy a dataset to a new history

---

bioblend/_tests/TestGalaxyHistories.py
bioblend/galaxy/histories/__init__.py

wip: method to import history from an archive or an url.

Import histories

---

bioblend/_tests/TestGalaxyUsers.py
bioblend/galaxy/users/__init__.py

Hi!
I needed a way to update user emails using the api, so here it is in bioblend

Add an update_user() method to UserClient

---

bioblend/galaxy/__init__.py

Add documentation on http basic auth for galaxy

---

bioblend/_tests/TestGalaxyTools.py
bioblend/galaxy/tools/__init__.py

Add a function to galaxy/tools named `requirements` to get `/api/tools/requirements/<tool_id>`

Add function for getting 'api/tools/requirements/<tool_id>'

---

bioblend/_tests/TestGalaxyHistories.py
bioblend/galaxy/histories/__init__.py

Fix https://github.com/galaxyproject/bioblend/issues/339

Add ``published`` parameter to ``HistoryClient.get_histories()``

---

ABOUT.rst

Fix https://github.com/galaxyproject/bioblend/issues/350 .

Add a note on how the name came to be

---

bioblend/galaxy/histories/__init__.py

Switch history

---

bioblend/galaxy/histories/__init__.py

Fixes https://github.com/galaxyproject/bioblend/issues/348.

Add copy_content method to allow copying a collection

---

bioblend/galaxy/datasets/__init__.py

I needed to download some errored datasets today and bioblend doesn't allow it, even though it's possible in the UI. It should be possible for the user to override this behaviour.
(It would be nice if this could work exactly like the UI, i.e. only allow downloading when the dataset displays the download symbol. Unfortunately this would require the `has_data` attribute to be exposed in the API, and it isn't currently. However, I think this is a very minor point.)

Allow download of non-ok datasets

---

bioblend/_tests/TestGalaxyHistories.py
bioblend/galaxy/histories/__init__.py

As discussed here: https://github.com/galaxyproject/bioblend/pull/341
Also adding the option to filter by `slug`.

Adding get_published_histories method

---

bioblend/_tests/TestGalaxyInvocations.py
bioblend/_tests/TestGalaxyJobs.py
bioblend/galaxy/invocations/__init__.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxy/workflows/__init__.py

Fixup workflow redux

---

bioblend/_tests/TestGalaxyWorkflows.py
bioblend/_tests/data/paste_columns_subworkflow.ga
bioblend/galaxy/workflows/__init__.py

Fix #321
I am not sure how to test this functionality because I do not know what kind of input would require this parameter to be set to True.

Expose parameters_normalized param in invoke_workflow

---

bioblend/_tests/TestGalaxyTools.py
bioblend/galaxy/tools/__init__.py

This PR improves the coverage of the Tools API with two new methods:
- `get_citations`
- `uninstall_dependencies`

Improve Tools API coverage

---

bioblend/_tests/TestGalaxyInvocations.py
bioblend/galaxy/invocations/__init__.py

See https://github.com/galaxyproject/galaxy/pull/11881

Fix for rerun_invocation method

---

bioblend/_tests/TestGalaxyJobs.py

`test_rerun_and_remap()` is the main culprit for #394, it fails in multiple different ways.
Hopefully this is an improvement. I ran it 100 times locally without seeing any failures.

Improve stability of test_rerun_and_remap() test

---

bioblend/toolshed/repositories/__init__.py

Fix https://github.com/galaxyproject/bioblend/issues/197

Add update_repository_metadata() method to ToolShedRepositoryClient

---

bioblend/_tests/TestGalaxyConfig.py
bioblend/galaxy/config/__init__.py

Add method to get /api/whoami and basic tests for bioblend.galaxy.config functions

Add whoami to bioblend.galaxy.config

---

bioblend/galaxy/groups/__init__.py

`groups`: Type Annotations

---

bioblend/_tests/GalaxyTestBase.py
bioblend/_tests/TestGalaxyDatasetCollections.py
bioblend/galaxy/dataset_collections/__init__.py

Type annotating `dataset_collections`.
Validating with: `tox -e lint `
Still working on this. Here is the result of the linting:
```bash
lint run-test: commands[0] | flake8 .
lint run-test: commands[1] | black --check --diff .
All done! ✨ 🍰 ✨
114 files would be left unchanged.
lint run-test: commands[2] | isort --check --diff .
Skipped 3 files
lint run-test: commands[3] | mypy bioblend/
bioblend/galaxy/dataset_collections/__init__.py:42: error: "Dict[str, Any]" has no attribute "to_dict"  [attr-defined]
return dict(name=self.name, collection_type=self.type, element_identifiers=[e.to_dict() for e in self.elements])
^
bioblend/galaxy/dataset_collections/__init__.py:51: error: "Dict[str, Any]" has no attribute "to_dict"  [attr-defined]
element_identifiers=[e.to_dict() for e in …
```

`dataset_collections`: Type Annotations

---

bioblend/galaxy/folders/__init__.py

`folders`: Type Annotations

---

bioblend/galaxy/genomes/__init__.py
bioblend/galaxy/quotas/__init__.py

added typing info, and made the other necessary changes to /bioblend/galaxy/genomes/__init__.py

Add type annotations to ``bioblend.galaxy.genomes``

---

bioblend/galaxy/libraries/__init__.py
bioblend/galaxy/roles/__init__.py

annotated libraries/__init__.py

Add type annotation to ``bioblend.galaxy.libraries`` and ``bioblend.galaxy.roles``

---

bioblend/galaxy/tools/__init__.py

Type annotation for tools/__init__.py

Type annotation added for bioblend/galaxy/tools

---

bioblend/galaxy/toolshed/__init__.py

annotation added for toolshed

---

bioblend/galaxy/users/__init__.py
bioblend/galaxy/visual/__init__.py

type annotation added for users

Add type annotation for ``bioblend.galaxy.users`` and ``bioblend.galaxy.visual``

---

bioblend/galaxy/workflows/__init__.py

Type annotation for workflows added

Type annotation for workflows added

---

bioblend/galaxy/histories/__init__.py
bioblend/toolshed/repositories/__init__.py
bioblend/util/__init__.py

Annotations for util added

---

bioblend/_tests/TestGalaxyDatasets.py
bioblend/_tests/TestGalaxyFolders.py
bioblend/_tests/TestGalaxyJobs.py
bioblend/_tests/TestGalaxyWorkflows.py
bioblend/_tests/test_util.py
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/folders/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/jobs/__init__.py
bioblend/galaxy/libraries/__init__.py
bioblend/galaxy/tools/__init__.py
bioblend/galaxy/workflows/__init__.py
setup.cfg

Leave out some modules that are not fully type annotated yet.

Enable ``check_untyped_defs`` for mypy and fix type annotations

---

bioblend/_tests/CloudmanTestBase.py
bioblend/_tests/TestCloudmanServices.py
bioblend/cloudman/__init__.py
setup.cfg

Type annotation: cloudman/__init__.py

Type annotation: cloudman/__init__.py

---

bioblend/galaxy/client.py
bioblend/galaxy/forms/__init__.py
bioblend/galaxyclient.py

Also:
- Fix broken ``FormsClient.create_form()`` method

Add type annotation to ``bioblend.galaxy.client``

---

bioblend/_tests/TestGalaxyObjects.py
bioblend/config.py
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/genomes/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/invocations/__init__.py
bioblend/galaxy/objects/client.py
bioblend/galaxy/objects/galaxy_instance.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxy/workflows/__init__.py
setup.cfg

Type annotating `bioblend.galaxy.objects`.
Validating with: `tox -e lint`
Linting produces a bunch of errors. I'm still working on this

`objects`: Type Annotations

---

bioblend/_tests/TestGalaxyHistories.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/jobs/__init__.py
bioblend/galaxy/tools/__init__.py

Add ``all`` parameter to ``HistoryClient.get_histories()``

---

bioblend/_tests/TestGalaxyObjects.py
bioblend/_tests/TestGalaxyToolDependencies.py
bioblend/galaxy/tool_dependencies/__init__.py

i.e. 
```
GET /api/dependency_resolvers/unused_paths
PUT /api/dependency_resolvers/unused_paths
```
lets see if I got this right

add tool-dependencies/unused_paths

---

bioblend/_tests/TestGalaxyConfig.py
bioblend/galaxy/config/__init__.py

Hi!
Adding this method that could be handy for a usegalaxy.fr script.
Not sure it's the best place, let me know if it should be somewhere else

Add reload_toolbox method

---

bioblend/_tests/TestGalaxyToolContainerResolution.py
bioblend/galaxy/__init__.py
bioblend/galaxy/container_resolution/__init__.py

Add container_resolution index, show, resolve, resolve_toolbox, resolve_toolbox_with_install.
I'm making this a draft because it still needs examples and tests.

Add container_resolution

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
ABOUT.rst
CONTRIBUTING.md
README.rst
bioblend/_tests/GalaxyTestBase.py
bioblend/_tests/TestGalaxyJobs.py
bioblend/_tests/TestGalaxyObjects.py
bioblend/galaxy/datasets/__init__.py
bioblend/galaxy/folders/__init__.py
bioblend/galaxy/genomes/__init__.py
bioblend/galaxy/histories/__init__.py
bioblend/galaxy/jobs/__init__.py
bioblend/galaxy/libraries/__init__.py
bioblend/galaxy/objects/client.py
bioblend/galaxy/objects/wrappers.py
bioblend/galaxy/quotas/__init__.py
bioblend/galaxy/tool_dependencies/__init__.py
bioblend/galaxy/tools/__init__.py
bioblend/galaxy/workflows/__init__.py
bioblend/toolshed/categories/__init__.py
bioblend/toolshed/repositories/__init__.py
pyproject.toml
run_bioblend_tests.sh
setup.cfg
tox.ini

which has reached end of life on 2023-06-27.

Drop support for Python 3.7
